### ISSUE TITLE
Contact #1

### ISSUE THREAD

**Issue by OmioRahman** [Dont-Copy-That-Floppy/OpenSea_API#1]
Dont-Copy-That-Floppy
I have heard you made your own video downloader in python.

How can I create one of my own . A youtube video downloader in python  from scratch.
and what basic knowledge would I need to create it ?

Can you put your own video downloader in the hub?

**Comment by Dont-Copy-That-Floppy** [comment]
what's your email? or telegram handle?

**Comment by OmioRahman** [comment]
Telegram handle @Rahmanomio256
